FROM node:alpine

ENV http_proxy http://10.125.115.11:3128
ENV https_proxy http://10.125.115.11:3128

#RUN mkdir -p /app 
WORKDIR /app

COPY package.json /app
RUN npm install
COPY . /app

CMD ["npm", "start"]

